######################################################################
# Automatically generated by qmake (2.00a) Mon 12. Mar 16:07:50 2007
######################################################################

TEMPLATE = app
TARGET += 
DESTDIR  = ../
DEPENDPATH += .
INCLUDEPATH += . \
               ../common/. 
CONFIG += console
QT += xml

# Input
HEADERS += 
SOURCES += main.cpp \
            ../common/*.cpp
