# TCL script automaticaly generated by POD
cd ../objs
project new testconfig.ise
# configure platform params
project set family spartan3a
project set device XC3S200A
project set package FT256
project set speed -4
project set {Preferred Language} VHDL
## add components sources file
# add top level sources file
xfile add ../synthesis/top_testconfig.vhd
xfile add ../synthesis/imx27_wb16_wrapper/imx27_wb16_wrapper.vhd
xfile add ../synthesis/rstgen_syscon/rstgen_syscon.vhd
xfile add ../synthesis/imx27_wb16_wrapper00_mwb16/imx27_wb16_wrapper00_mwb16_intercon.vhd
xfile add ../synthesis/spartan_select_map/spartan_selectmap.vhd
# add constraint file
xfile add ../synthesis/testconfig.ucf 
process run "Generate Programming File"
process run "Generate Post-Synthesis Simulation Model"
process run "Generate Post-Place & Route Simulation Model"
