---------------------------------------------------------------------------
-- Company     : Automaticaly generated by POD
-- Author(s)   : 
-- 
-- Creation Date : 2010-10-21
-- File          : Top_testconfig.vhd
--
-- Abstract : 
-- insert a description here
--
---------------------------------------------------------------------------

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.numeric_std.all;

entity top_testconfig is

    port
    (
    -- imx27_wb16_wrapper00-eim
        imx27_wb16_wrapper00_imx_cs_n : in std_logic;
    -- imx27_wb16_wrapper00-eim
        imx27_wb16_wrapper00_imx_data : inout std_logic_vector(15 downto 0);
    -- rstgen_syscon00-clk_ext
        rstgen_syscon00_ext_clk : in std_logic;
    -- imx27_wb16_wrapper00-eim
        imx27_wb16_wrapper00_imx_eb0_n : in std_logic;
    -- imx27_wb16_wrapper00-eim
        imx27_wb16_wrapper00_imx_oe_n : in std_logic;
    -- imx27_wb16_wrapper00-eim
        imx27_wb16_wrapper00_imx_address : in std_logic_vector(11 downto 0);
    -- spartanconf-selectmap
        spartanconf_selectmap_data : inout std_logic_vector(15 downto 0);
    -- spartanconf-selectmap
        spartanconf_selectmap_busy : in std_logic;
    -- spartanconf-selectmap
        spartanconf_selectmap_init_n : in std_logic;
    -- spartanconf-selectmap
        spartanconf_selectmap_csi_n : inout std_logic;
    -- spartanconf-selectmap
        spartanconf_selectmap_done : in std_logic;
    -- spartanconf-selectmap
        spartanconf_selectmap_cclk : inout std_logic;
    -- spartanconf-selectmap
        spartanconf_selectmap_rdwr_n : inout std_logic;
    -- spartanconf-selectmap
        spartanconf_selectmap_program_n : inout std_logic;
    -- spartanconf-selectmap
        spartanconf_selectmap_spare1 : in std_logic ;
    -- spartanconf-selectmap
        spartanconf_selectmap_spare2 : in std_logic ;
    -- spartanconf-selectmap
        spartanconf_selectmap_spare3 : in std_logic

    );
end entity top_testconfig;

architecture top_testconfig_1 of top_testconfig is
    -------------------------
    -- declare components  --
    -------------------------


    component imx27_wb16_wrapper00_mwb16
        port (
            -- spartanconf_wbs
            spartanconf_wbs_add  : out std_logic_vector(1 downto 0);
            spartanconf_wbs_writedata  : out std_logic_vector(15 downto 0);
            spartanconf_wbs_readdata  : in std_logic_vector(15 downto 0);
            spartanconf_wbs_strobe  : out std_logic;
            spartanconf_wbs_cycle  : out std_logic;
            spartanconf_wbs_write  : out std_logic;
            spartanconf_wbs_ack  : in std_logic;
            -- spartanconf_candr
            spartanconf_clk  : out std_logic;
            spartanconf_reset  : out std_logic;
            -- imx27_wb16_wrapper00_mwb16
            imx27_wb16_wrapper00_wbm_address  : in std_logic_vector(12 downto 0);
            imx27_wb16_wrapper00_wbm_readdata  : out std_logic_vector(15 downto 0);
            imx27_wb16_wrapper00_wbm_writedata  : in std_logic_vector(15 downto 0);
            imx27_wb16_wrapper00_wbm_strobe  : in std_logic;
            imx27_wb16_wrapper00_wbm_write  : in std_logic;
            imx27_wb16_wrapper00_wbm_ack  : out std_logic;
            imx27_wb16_wrapper00_wbm_cycle  : in std_logic;
            -- imx27_wb16_wrapper00_candr
            imx27_wb16_wrapper00_gls_reset  : out std_logic;
            imx27_wb16_wrapper00_gls_clk  : out std_logic;
            -- rstgen_syscon00_imx27_wb16_wrapper00
            rstgen_syscon00_gls_clk  : in std_logic;
            rstgen_syscon00_gls_reset  : in std_logic
        );
    end component;

    component spartan_select_map
        generic(
            id : natural := 1;
            wb_size : natural := 16;
            clk_freq : natural := 100000
        );
        port (
            -- candr
            clk  : in std_logic;
            reset  : in std_logic;
            -- wbs
            wbs_add  : in std_logic_vector(1 downto 0);
            wbs_writedata  : in std_logic_vector(15 downto 0);
            wbs_readdata  : out std_logic_vector(15 downto 0);
            wbs_strobe  : in std_logic;
            wbs_cycle  : in std_logic;
            wbs_write  : in std_logic;
            wbs_ack  : out std_logic;
            -- selectmap
            selectmap_data       : inout std_logic_vector(15 downto 0);
            selectmap_csi_n      : inout std_logic;
            selectmap_rdwr_n     : inout std_logic;
            selectmap_cclk       : inout std_logic;
            selectmap_program_n  : inout std_logic;
            selectmap_init_n: in std_logic;
            selectmap_busy  : in std_logic;
            selectmap_done  : in std_logic;
            selectmap_spare1: in std_logic;
            selectmap_spare2: in std_logic;
            selectmap_spare3: in std_logic 
        );
    end component;

    component imx27_wb16_wrapper
        port (
            -- eim
            imx_address  : in std_logic_vector(11 downto 0);
            imx_data  : inout std_logic_vector(15 downto 0);
            imx_cs_n  : in std_logic;
            imx_oe_n  : in std_logic;
            imx_eb0_n  : in std_logic;
            -- candr
            gls_reset  : in std_logic;
            gls_clk  : in std_logic;
            -- mwb16
            wbm_address  : out std_logic_vector(12 downto 0);
            wbm_readdata  : in std_logic_vector(15 downto 0);
            wbm_writedata  : out std_logic_vector(15 downto 0);
            wbm_strobe  : out std_logic;
            wbm_write  : out std_logic;
            wbm_ack  : in std_logic;
            wbm_cycle  : out std_logic
        );
    end component;

    component rstgen_syscon
        port (
            -- candr
            gls_clk  : out std_logic;
            gls_reset  : out std_logic;
            -- clk_ext
            ext_clk  : in std_logic
        );
    end component;
    -------------------------
    -- Signals declaration
    -------------------------

    -- imx27_wb16_wrapper00
    -- eim
    -- candr
    signal imx27_wb16_wrapper00_gls_reset :  std_logic;
    signal imx27_wb16_wrapper00_gls_clk :  std_logic;
    -- mwb16
    signal imx27_wb16_wrapper00_wbm_address :  std_logic_vector(12 downto 0);
    signal imx27_wb16_wrapper00_wbm_readdata :  std_logic_vector(15 downto 0);
    signal imx27_wb16_wrapper00_wbm_writedata :  std_logic_vector(15 downto 0);
    signal imx27_wb16_wrapper00_wbm_strobe :  std_logic;
    signal imx27_wb16_wrapper00_wbm_write :  std_logic;
    signal imx27_wb16_wrapper00_wbm_ack :  std_logic;
    signal imx27_wb16_wrapper00_wbm_cycle :  std_logic;

    -- rstgen_syscon00
    -- candr
    signal rstgen_syscon00_gls_clk :  std_logic;
    signal rstgen_syscon00_gls_reset :  std_logic;
    -- clk_ext

    -- spartanconf
    -- candr
    signal spartanconf_clk :  std_logic;
    signal spartanconf_reset :  std_logic;
    -- wbs
    signal spartanconf_wbs_add :  std_logic_vector(1 downto 0);
    signal spartanconf_wbs_writedata :  std_logic_vector(15 downto 0);
    signal spartanconf_wbs_readdata :  std_logic_vector(15 downto 0);
    signal spartanconf_wbs_strobe :  std_logic;
    signal spartanconf_wbs_cycle :  std_logic;
    signal spartanconf_wbs_write :  std_logic;
    signal spartanconf_wbs_ack :  std_logic;
    -- selectmap

    -- imx27_wb16_wrapper00_mwb16_intercon
    -- spartanconf_wbs
    signal imx27_wb16_wrapper00_mwb16_intercon_spartanconf_wbs_add :  std_logic_vector(1 downto 0);
    signal imx27_wb16_wrapper00_mwb16_intercon_spartanconf_wbs_writedata :  std_logic_vector(15 downto 0);
    signal imx27_wb16_wrapper00_mwb16_intercon_spartanconf_wbs_readdata :  std_logic_vector(15 downto 0);
    signal imx27_wb16_wrapper00_mwb16_intercon_spartanconf_wbs_strobe :  std_logic;
    signal imx27_wb16_wrapper00_mwb16_intercon_spartanconf_wbs_cycle :  std_logic;
    signal imx27_wb16_wrapper00_mwb16_intercon_spartanconf_wbs_write :  std_logic;
    signal imx27_wb16_wrapper00_mwb16_intercon_spartanconf_wbs_ack :  std_logic;
    -- spartanconf_candr
    signal imx27_wb16_wrapper00_mwb16_intercon_spartanconf_clk :  std_logic;
    signal imx27_wb16_wrapper00_mwb16_intercon_spartanconf_reset :  std_logic;
    -- imx27_wb16_wrapper00_mwb16
    signal imx27_wb16_wrapper00_mwb16_intercon_imx27_wb16_wrapper00_wbm_address :  std_logic_vector(12 downto 0);
    signal imx27_wb16_wrapper00_mwb16_intercon_imx27_wb16_wrapper00_wbm_readdata :  std_logic_vector(15 downto 0);
    signal imx27_wb16_wrapper00_mwb16_intercon_imx27_wb16_wrapper00_wbm_writedata :  std_logic_vector(15 downto 0);
    signal imx27_wb16_wrapper00_mwb16_intercon_imx27_wb16_wrapper00_wbm_strobe :  std_logic;
    signal imx27_wb16_wrapper00_mwb16_intercon_imx27_wb16_wrapper00_wbm_write :  std_logic;
    signal imx27_wb16_wrapper00_mwb16_intercon_imx27_wb16_wrapper00_wbm_ack :  std_logic;
    signal imx27_wb16_wrapper00_mwb16_intercon_imx27_wb16_wrapper00_wbm_cycle :  std_logic;
    -- imx27_wb16_wrapper00_candr
    signal imx27_wb16_wrapper00_mwb16_intercon_imx27_wb16_wrapper00_gls_reset :  std_logic;
    signal imx27_wb16_wrapper00_mwb16_intercon_imx27_wb16_wrapper00_gls_clk :  std_logic;
    -- rstgen_syscon00_imx27_wb16_wrapper00
    signal imx27_wb16_wrapper00_mwb16_intercon_rstgen_syscon00_gls_clk :  std_logic;
    signal imx27_wb16_wrapper00_mwb16_intercon_rstgen_syscon00_gls_reset :  std_logic;

    -- void pins

begin

    -------------------
    --  Set forces   --
    -------------------

    -------------------------
    -- declare instances
    -------------------------

    imx27_wb16_wrapper00 : imx27_wb16_wrapper
    port map (
            -- eim
            imx_address => imx27_wb16_wrapper00_imx_address,
            imx_data => imx27_wb16_wrapper00_imx_data,
            imx_cs_n => imx27_wb16_wrapper00_imx_cs_n,
            imx_oe_n => imx27_wb16_wrapper00_imx_oe_n,
            imx_eb0_n => imx27_wb16_wrapper00_imx_eb0_n,
            -- candr
            gls_reset => imx27_wb16_wrapper00_gls_reset,
            gls_clk => imx27_wb16_wrapper00_gls_clk,
            -- mwb16
            wbm_address => imx27_wb16_wrapper00_wbm_address,
            wbm_readdata => imx27_wb16_wrapper00_wbm_readdata,
            wbm_writedata => imx27_wb16_wrapper00_wbm_writedata,
            wbm_strobe => imx27_wb16_wrapper00_wbm_strobe,
            wbm_write => imx27_wb16_wrapper00_wbm_write,
            wbm_ack => imx27_wb16_wrapper00_wbm_ack,
            wbm_cycle => imx27_wb16_wrapper00_wbm_cycle
            );

    rstgen_syscon00 : rstgen_syscon
    port map (
            -- candr
            gls_clk => rstgen_syscon00_gls_clk,
            gls_reset => rstgen_syscon00_gls_reset,
            -- clk_ext
            ext_clk => rstgen_syscon00_ext_clk
            );

    spartanconf : spartan_select_map
    generic map (
            id => 1,
            wb_size => 16,
            clk_freq => 100000
        )
    port map (
            -- candr
            clk => spartanconf_clk,
            reset => spartanconf_reset,
            -- wbs
            wbs_add => spartanconf_wbs_add,
            wbs_writedata => spartanconf_wbs_writedata,
            wbs_readdata => spartanconf_wbs_readdata,
            wbs_strobe => spartanconf_wbs_strobe,
            wbs_cycle => spartanconf_wbs_cycle,
            wbs_write => spartanconf_wbs_write,
            wbs_ack => spartanconf_wbs_ack,
            -- selectmap
            selectmap_data => spartanconf_selectmap_data,
            selectmap_csi_n => spartanconf_selectmap_csi_n,
            selectmap_rdwr_n => spartanconf_selectmap_rdwr_n,
            selectmap_cclk => spartanconf_selectmap_cclk,
            selectmap_program_n => spartanconf_selectmap_program_n,
            selectmap_init_n => spartanconf_selectmap_init_n,
            selectmap_busy => spartanconf_selectmap_busy,
            selectmap_done => spartanconf_selectmap_done,
            selectmap_spare1 => spartanconf_selectmap_spare1,
            selectmap_spare2 => spartanconf_selectmap_spare2,
            selectmap_spare3 => spartanconf_selectmap_spare3
            );

    imx27_wb16_wrapper00_mwb16_intercon : imx27_wb16_wrapper00_mwb16
    port map (
            -- spartanconf_wbs
            spartanconf_wbs_add => imx27_wb16_wrapper00_mwb16_intercon_spartanconf_wbs_add,
            spartanconf_wbs_writedata => imx27_wb16_wrapper00_mwb16_intercon_spartanconf_wbs_writedata,
            spartanconf_wbs_readdata => imx27_wb16_wrapper00_mwb16_intercon_spartanconf_wbs_readdata,
            spartanconf_wbs_strobe => imx27_wb16_wrapper00_mwb16_intercon_spartanconf_wbs_strobe,
            spartanconf_wbs_cycle => imx27_wb16_wrapper00_mwb16_intercon_spartanconf_wbs_cycle,
            spartanconf_wbs_write => imx27_wb16_wrapper00_mwb16_intercon_spartanconf_wbs_write,
            spartanconf_wbs_ack => imx27_wb16_wrapper00_mwb16_intercon_spartanconf_wbs_ack,
            -- spartanconf_candr
            spartanconf_clk => imx27_wb16_wrapper00_mwb16_intercon_spartanconf_clk,
            spartanconf_reset => imx27_wb16_wrapper00_mwb16_intercon_spartanconf_reset,
            -- imx27_wb16_wrapper00_mwb16
            imx27_wb16_wrapper00_wbm_address => imx27_wb16_wrapper00_mwb16_intercon_imx27_wb16_wrapper00_wbm_address,
            imx27_wb16_wrapper00_wbm_readdata => imx27_wb16_wrapper00_mwb16_intercon_imx27_wb16_wrapper00_wbm_readdata,
            imx27_wb16_wrapper00_wbm_writedata => imx27_wb16_wrapper00_mwb16_intercon_imx27_wb16_wrapper00_wbm_writedata,
            imx27_wb16_wrapper00_wbm_strobe => imx27_wb16_wrapper00_mwb16_intercon_imx27_wb16_wrapper00_wbm_strobe,
            imx27_wb16_wrapper00_wbm_write => imx27_wb16_wrapper00_mwb16_intercon_imx27_wb16_wrapper00_wbm_write,
            imx27_wb16_wrapper00_wbm_ack => imx27_wb16_wrapper00_mwb16_intercon_imx27_wb16_wrapper00_wbm_ack,
            imx27_wb16_wrapper00_wbm_cycle => imx27_wb16_wrapper00_mwb16_intercon_imx27_wb16_wrapper00_wbm_cycle,
            -- imx27_wb16_wrapper00_candr
            imx27_wb16_wrapper00_gls_reset => imx27_wb16_wrapper00_mwb16_intercon_imx27_wb16_wrapper00_gls_reset,
            imx27_wb16_wrapper00_gls_clk => imx27_wb16_wrapper00_mwb16_intercon_imx27_wb16_wrapper00_gls_clk,
            -- rstgen_syscon00_imx27_wb16_wrapper00
            rstgen_syscon00_gls_clk => imx27_wb16_wrapper00_mwb16_intercon_rstgen_syscon00_gls_clk,
            rstgen_syscon00_gls_reset => imx27_wb16_wrapper00_mwb16_intercon_rstgen_syscon00_gls_reset
            );

    ---------------------------
    -- instances connections --
    ---------------------------

    -- connect imx27_wb16_wrapper00
        -- eim
        -- candr
        imx27_wb16_wrapper00_gls_reset <= imx27_wb16_wrapper00_mwb16_intercon_imx27_wb16_wrapper00_gls_reset;
        imx27_wb16_wrapper00_gls_clk <= imx27_wb16_wrapper00_mwb16_intercon_imx27_wb16_wrapper00_gls_clk;
        -- mwb16
        imx27_wb16_wrapper00_wbm_readdata <= imx27_wb16_wrapper00_mwb16_intercon_imx27_wb16_wrapper00_wbm_readdata;
        imx27_wb16_wrapper00_wbm_ack <= imx27_wb16_wrapper00_mwb16_intercon_imx27_wb16_wrapper00_wbm_ack;

    -- connect rstgen_syscon00
        -- candr
        -- clk_ext

    -- connect spartanconf
        -- candr
        spartanconf_clk <= imx27_wb16_wrapper00_mwb16_intercon_spartanconf_clk;
        spartanconf_reset <= imx27_wb16_wrapper00_mwb16_intercon_spartanconf_reset;
        -- wbs
        spartanconf_wbs_add <= imx27_wb16_wrapper00_mwb16_intercon_spartanconf_wbs_add;
        spartanconf_wbs_writedata <= imx27_wb16_wrapper00_mwb16_intercon_spartanconf_wbs_writedata;
        spartanconf_wbs_strobe <= imx27_wb16_wrapper00_mwb16_intercon_spartanconf_wbs_strobe;
        spartanconf_wbs_cycle <= imx27_wb16_wrapper00_mwb16_intercon_spartanconf_wbs_cycle;
        spartanconf_wbs_write <= imx27_wb16_wrapper00_mwb16_intercon_spartanconf_wbs_write;
        -- selectmap

    -- connect imx27_wb16_wrapper00_mwb16_intercon
        -- spartanconf_wbs
        imx27_wb16_wrapper00_mwb16_intercon_spartanconf_wbs_readdata <= spartanconf_wbs_readdata;
        imx27_wb16_wrapper00_mwb16_intercon_spartanconf_wbs_ack <= spartanconf_wbs_ack;
        -- spartanconf_candr
        -- imx27_wb16_wrapper00_mwb16
        imx27_wb16_wrapper00_mwb16_intercon_imx27_wb16_wrapper00_wbm_address <= imx27_wb16_wrapper00_wbm_address;
        imx27_wb16_wrapper00_mwb16_intercon_imx27_wb16_wrapper00_wbm_writedata <= imx27_wb16_wrapper00_wbm_writedata;
        imx27_wb16_wrapper00_mwb16_intercon_imx27_wb16_wrapper00_wbm_strobe <= imx27_wb16_wrapper00_wbm_strobe;
        imx27_wb16_wrapper00_mwb16_intercon_imx27_wb16_wrapper00_wbm_write <= imx27_wb16_wrapper00_wbm_write;
        imx27_wb16_wrapper00_mwb16_intercon_imx27_wb16_wrapper00_wbm_cycle <= imx27_wb16_wrapper00_wbm_cycle;
        -- imx27_wb16_wrapper00_candr
        -- rstgen_syscon00_imx27_wb16_wrapper00
        imx27_wb16_wrapper00_mwb16_intercon_rstgen_syscon00_gls_clk <= rstgen_syscon00_gls_clk;
        imx27_wb16_wrapper00_mwb16_intercon_rstgen_syscon00_gls_reset <= rstgen_syscon00_gls_reset;

end architecture top_testconfig_1;
