#############################################################
#
# PPS Utilities & Test scripts
#
#############################################################

ARMADEUS-PPS_CONFIGS_DIR:=$(TOPDIR)/../target/pps/configs
ARMADEUS-PPS_CONFIGS_TARGET_DIR:=$(TARGET_DIR)/etc/
ARMADEUS-PPS_INITS_DIR:=$(TOPDIR)/../target/pps/init
ARMADEUS-PPS_INITS_TARGET_DIR:=$(ARMADEUS-PPS_CONFIGS_TARGET_DIR)/init.d
ARMADEUS-PPS_HOME_DIR:=$(TOPDIR)/../target/pps/home
ARMADEUS-PPS_HOME_TARGET_DIR:=$(TARGET_DIR)/home

ARMADEUS-PPS_TESTSCRIPTS_SOURCE:=$(TOPDIR)/../target/pps/scripts
ARMADEUS-PPS_TESTSCRIPTS_TARGET_DIR:=$(TARGET_DIR)/usr/local/pps/scripts
ARMADEUS-PPS_TESTSCRIPTS_WWW_DIR:=$(ARMADEUS-PPS_TESTSCRIPTS_SOURCE)/www
ARMADEUS-PPS_TESTSCRIPTS_WWW_TARGET_DIR:=$(TARGET_DIR)/var
ARMADEUS-PPS_TESTSCRIPTS_CONFIGS_DIR:=$(ARMADEUS-PPS_TESTSCRIPTS_SOURCE)/configs
ARMADEUS-PPS_TESTSCRIPTS_CONFIGS_TARGET_DIR:=$(ARMADEUS-PPS_CONFIGS_TARGET_DIR)

$(ARMADEUS-PPS_INITS_TARGET_DIR)/S80gpios:
	cp -Rf $(ARMADEUS-PPS_INITS_DIR)/* $(ARMADEUS-PPS_INITS_TARGET_DIR)

pps-home:
	cp -Rf $(ARMADEUS-PPS_HOME_DIR)/* $(ARMADEUS-PPS_HOME_TARGET_DIR)

pps-configs:
	mkdir -p $(ARMADEUS-PPS_CONFIGS_TARGET_DIR)
	cp -Rf $(ARMADEUS-PPS_CONFIGS_DIR)/* $(ARMADEUS-PPS_CONFIGS_TARGET_DIR)

$(ARMADEUS-PPS_TESTSCRIPTS_TARGET_DIR)/init_boa.sh:
ifeq ($(BR2_PACKAGE_ARMADEUS_PPS_TEST_SCRIPTS),y)
	$(ARMADEUS-PPS_TESTSCRIPTS_SOURCE)/install.sh $(ARMADEUS-PPS_TESTSCRIPTS_TARGET_DIR)
endif

$(ARMADEUS-PPS_TESTSCRIPTS_WWW_TARGET_DIR)/www/index.html:
ifeq ($(BR2_PACKAGE_ARMADEUS_PPS_TEST_SCRIPTS),y)
	cp -Rf $(ARMADEUS-PPS_TESTSCRIPTS_WWW_DIR) $(ARMADEUS-PPS_TESTSCRIPTS_WWW_TARGET_DIR)
endif

$(ARMADEUS-PPS_TESTSCRIPTS_CONFIGS_TARGET_DIR)/ipsec-tools.conf:
ifeq ($(BR2_PACKAGE_ARMADEUS_PPS_TEST_SCRIPTS),y)
	cp -Rf $(ARMADEUS-PPS_TESTSCRIPTS_CONFIGS_DIR)/* $(ARMADEUS-PPS_TESTSCRIPTS_CONFIGS_TARGET_DIR)
endif

pps-utils: $(ARMADEUS-PPS_INITS_TARGET_DIR)/S80gpios pps-home pps-configs $(ARMADEUS-PPS_TESTSCRIPTS_TARGET_DIR)/init_boa.sh $(ARMADEUS-PPS_TESTSCRIPTS_WWW_TARGET_DIR)/www/index.html $(ARMADEUS-PPS_TESTSCRIPTS_CONFIGS_TARGET_DIR)/ipsec-tools.conf

armadeus-pps-utils-clean:
	rm -rf $(ARMADEUS-PPS_TESTSCRIPTS_TARGET_DIR)
	rm -rf $(ARMADEUS-PPS_WWW_TARGET_DIR)/www

#############################################################
#
# Toplevel Makefile options
#
#############################################################
ifeq ($(strip $(BR2_PACKAGE_ARMADEUS_PPS_UTILITIES)),y)
TARGETS+=pps-utils
endif
